app = ""

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  RUNTIME_ENV = "deno"
  DENO_ENV = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  doh = "run --allow-net --allow-env --import-map=import_map.json http.ts"

# DNS over HTTP
[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["doh"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
