name = "serverless-dns"
route = ""
type = "webpack"
account_id = ""
workers_dev = true
zone_id = ""
compatibility_date = "2021-09-21"
webpack_config = "webpack.config.cjs"

[vars]
WORKER_TIMEOUT = 10000
CLOUD_PLATFORM = "cloudflare"
LOG_LEVEL = "debug"
CF_BLOCKLIST_DOWNLOAD_TIMEOUT = 5000
RUNTIME = "worker"
WORKER_ENV = "development"
CF_BLOCKLIST_URL = "https://cf.rethinkdns.com/blocklists/"
CF_LATEST_BLOCKLIST_TIMESTAMP = "1642484493505"
CF_DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
TD_NODE_COUNT = 40212525
TD_PARTS = 2

##################
#------PROD------#
##################
# wrangler doesn't yet support Workers Services and the new "Environments"
# github.com/cloudflare/cloudflare-docs/pull/3175/files
# github.com/cloudflare/wrangler2/issues/27
# developers.cloudflare.com/workers/platform/environments
[env.prod]
name = "basic-unbound"
routes = [
  "basic.rethinkdns.com/*",
  "basic.bravedns.com/*",
]
# vars are not inherited
# workers/platform/environment-variables#environment-variables-via-wrangler
[env.prod.vars]
WORKER_TIMEOUT = 10000
CLOUD_PLATFORM = "cloudflare"
LOG_LEVEL = "debug"
CF_BLOCKLIST_DOWNLOAD_TIMEOUT = 5000
RUNTIME = "worker"
WORKER_ENV = "production"
CF_BLOCKLIST_URL = "https://cf.rethinkdns.com/blocklists/"
CF_LATEST_BLOCKLIST_TIMESTAMP = "1642484493505"
CF_DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
TD_NODE_COUNT = 40212525
TD_PARTS = 2
