name: 🪂 Fly

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/fly.yml"
      - ".env.example"
      - ".eslintrc.cjs"
      - ".prettierignore"
      - "wrangler.toml"
      - "README.md"
      - "wrangler.toml"
      - ".vscode/*"
      - ".husky/*"
      - ".prettierrc.json"
      - "LICENSE"
      - "run"
  workflow_dispatch:
    inputs:
      git-ref:
        description: "Branch / ref / tag to build"
        required: false
        default: "main"
      deployment-type:
        description: "Deployment: dev || live || b1"
        required: false
        default: "dev"

env:
  GIT_REF: ${{ github.event.inputs.git-ref || github.ref }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  # default fly app to deploy to (typically, dev)
  FLY_APP: ${{ secrets.FLY_APP_NAME }}
  FLY_PROD_APP: ${{ secrets.FLY_APP_NAME_LIVE }}
  FLY_B1_APP: ${{secrets.FLY_APP_NAME_B1 }}

jobs:
  deploy:
    name: 🚀 Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GIT_REF }}
      - run: |
          echo "GIT_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: ⚠ B1 via Dispatch?
        if: ${{ github.event_name == 'workflow_dispatch' &&
          github.event.inputs.deployment-type == 'b1' }}
        run: |
          echo "FLY_APP=${FLY_B1_APP}" >> $GITHUB_ENV
          echo "::notice::Deploying ${FLY_B1_APP} / ${GIT_REF} @ ${COMMIT_SHA}"
        shell: bash
        env:
          COMMIT_SHA: ${{ github.sha }}

      - name: 🚨 Prod via Dispatch?
        if: ${{ github.event_name == 'workflow_dispatch' &&
          github.event.inputs.deployment-type == 'live' }}
        run: |
          echo "FLY_APP=${FLY_PROD_APP}" >> $GITHUB_ENV
          echo "::notice::Deploying ${FLY_PROD_APP} / ${GIT_REF} @ ${COMMIT_SHA}"
        shell: bash
        env:
          COMMIT_SHA: ${{ github.sha }}

      - name: 🚨 Prod via Tag?
        # docs.github.com/en/actions/learn-github-actions/contexts#github-context
        if: github.ref_type == 'tag'
        run: |
          echo "FLY_APP=${FLY_PROD_APP}" >> $GITHUB_ENV
          echo "::notice::Deploying ${FLY_PROD_APP} / ${GIT_REF} @ ${COMMIT_SHA}"
        shell: bash
        env:
          COMMIT_SHA: ${{ github.sha }}

      - name: 🏗 Build & 🚢 Ship
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy
            --dockerfile node.Dockerfile
            --image-label ${{ env.GIT_HEAD }}
            --strategy rolling
            "
      - run: |
          echo "::notice::Image @ registry.fly.io/${{ env.FLY_APP }}:${{ env.GIT_HEAD }}"
