name: 🪰 Fly

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      git-ref:
        description: "Branch / ref / tag to build"
        required: false
        default: "main"
      deployment:
        description: "Deployment: dev || live || b1"
        required: false
        default: "dev"

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP: ${{ secrets.FLY_APP_NAME }}

jobs:
  deploy:
    name: 🚀 Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git-ref || github.ref }}

      - name: ⚠️ *B1* Fly App ?
        if: ${{ github.event_name == 'workflow_dispatch' &&
          github.event.inputs.deployment == 'b1' }}
        run: |
          echo "FLY_APP=${{ secrets.FLY_APP_NAME_B1 }}" >> $GITHUB_ENV

      - name: 🚨 *LIVE* Fly App ?
        if: ${{ github.event_name == 'workflow_dispatch' &&
          github.event.inputs.deployment == 'live' }}
        run: |
          echo "FLY_APP=${{ secrets.FLY_APP_NAME_LIVE }}" >> $GITHUB_ENV

      - name: 🏗️ Build & 🚢 Ship
        uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy --dockerfile node.Dockerfile"
