name: Profiler

on:
  push:
    branches:
      - "main"
    paths:
      - './src/**'

  workflow_dispatch:
    inputs:
      git-ref:
        description: "git tip: branch/ref/tag"
        required: false
        default: "main"
      js-runtime:
        description: "proc: deno/node"
        required: false
        default: "node"
      maxtime:
        description: "run time (in seconds)"
        required: false
        default: "120s"

env:
  GIT_REF: ${{ github.event.inputs.git-ref || github.ref }}
  JS_RUNTIME: ${{ github.event.inputs.js-runtime || "node" }}
  MAXTIME_SEC: ${{ github.event.inputs.maxtime || "60s" }}
  NODE_VER: "17.x"
  QDOH: {{ "q" }}

jobs:
  deploy:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: $GIT_REF
      - run: |
          echo "GIT_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV

      # docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python
      - name: Setup Node $NODE_VER
        if: $JS_RUNTIME == 'node'
        uses: actions/setup-node@v2
        with:
          node-version: $NODE_VER

      # deno.land/#installation
      - name: Setup Deno @latest
        if: $JS_RUNTIME == 'deno'
        run: |
          echo "::notice::deno install unsafe"
          curl -fsSL https://deno.land/install.sh | sh
        shell: bash

      - name: Deps
        run: npm ci
      - run: npm run build --if-present

      # github.com/natesales/as112/blob/8335fbf/roles/packages/tasks/main.yml#L11
      - name: Setup apt
        apt_repository:
          repo: deb [trusted=yes] https://repo.natesales.net/apt /
          state: present

      - name: Install qdoh
        apt:
          update_cache: true
          pkg:
            - q

      - name: Run profiler
      - if: success()
      - run: |
          timeout $MAXTIME_SEC ./run $JS_RUNTIME p1
        shell: bash
